#!/bin/bash

# Wrapper script for OzSTAR

# Load the python module
ml gcc/12.3.0 python/3.11.3

# Location of script
SCRIPT=$(realpath "$0")
SCRIPT_PATH=$(dirname "$SCRIPT")

# Run main script
"${SCRIPT_PATH}/jobsummary.sh" "$@"
